# Generated by Django 5.1.5 on 2025-03-12 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievance_portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_type', models.CharField(choices=[('Academic', 'Academic'), ('Hostel', 'Hostel'), ('Mess', 'Mess'), ('Facilities', 'Facilities'), ('Faculties', 'Faculties'), ('Canteen', 'Canteen'), ('Others', 'Others')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('anonymous', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='grievance_portal.student')),
            ],
        ),
    ]
