# Generated by Django 5.1.5 on 2025-03-12 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievance_portal', '0002_complaint'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='prn',
            new_name='student',
        ),
        migrations.AddField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
