# Generated by Django 5.1.5 on 2025-03-12 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grievance_portal', '0003_rename_prn_complaint_student_complaint_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='student',
            new_name='prn',
        ),
    ]
