# Generated by Django 5.1.5 on 2025-03-14 02:54

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievance_portal', '0005_alter_complaint_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('url', models.URLField(blank=True, null=True)),
                ('query_type', models.CharField(choices=[('Bug/Error', 'Bug/Error'), ('UI Issue', 'UI Issue'), ('Login Issue', 'Login Issue'), ('Feature Request', 'Feature Request'), ('Other', 'Other')], max_length=50)),
                ('module', models.CharField(choices=[('Login', 'Login'), ('Dashboard', 'Dashboard'), ('Complaint Management', 'Complaint Management'), ('Profile', 'Profile'), ('Other', 'Other')], max_length=50)),
                ('evidence', models.ImageField(blank=True, null=True, upload_to='query_evidence/')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('prn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grievance_portal.student')),
            ],
        ),
    ]
